### ISSUE TITLE
Markdown语法的规范问题

### ISSUE THREAD

**Issue by mushroom-x** [se7enXF/pyside2#1]
Markdown的每个符号， 都是有其语义的（就像HTML标签一样）

另外，不同的部分在文章中的顺序， 也可以规范一下。 例如参考文献一般在后面。

把第一篇文章修改了一下， 大概长这样： 

# 环境配置与入门

## 概要

> 这里可以写一下， 这篇文章主要的目的是什么
## 软件开发环境  

* Python3.6  
* PySide2

> 操作系统相关环境

## 安装PySide2  

关于Python的安装请自行学习，这里不再累述。  
安装PySide2的PyPI，命令行:  

```bash
pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.11/
latest/ pyside2 --trusted-host download.qt.io*  
```

> bash指令可以放在code代码块里面。

## 下集预告：Hello world!  

万程开头helloworld!作者编写的的这个helloworld.py是根据官网教程改编的，里面也写了详细的注释。
此方法，只使用编写代码来实现Qt窗口。当我们设计复杂且美观的窗口时，只使用代码来编写必定是非常繁琐的。
因此，在下一讲中，会介绍一种结合QtDesigner的用户界面绘制方法，能让我们更高效的实现QtUI。
当你配置好环境，可以直接运行helloworld.py，如果成功运行并显示如下窗口，那么恭喜你入坑！  
![hello_world](../Addition/Lesson1.png)

## 参考文档  

[PySide官方文档 Qt for Python](https://doc-snapshots.qt.io/qtforpython/index.html )

**Comment by se7enXF** [comment]
优秀！我只是没时间整理，赶紧只写出来了一些要点。
