### ISSUE TITLE
How to passing parameters by 'connectSlotsByName' connection method

### ISSUE THREAD

**Issue by se7enXF** [se7enXF/pyside2#2]
### 传参问题  

我在使用`connectSlotsByName`方法进行槽连接时，发现不能传参。求助。

**Comment by se7enXF** [comment]
## 解决办法  
```python
# 连接函数
self.contextMenu.triggered.connect(self.menuSlot)

# 槽函数
def menuSlot(self, act):
    pass
```
从上述代码中我得到启发，使用`connectSlotsByName`方式连接信号时，只需要指定槽函数的参数与信号一致即可。     
但是我在测试时某些控件不适用此方法，比如说QTabWidget.currentChanged，只能使用connect方式才起作用。    
求助。

**Comment by dexter2406** [comment]
博主找到解决方法了吗？

**Comment by dexter2406** [comment]
在此感谢一下楼主，由于PySide2没PyQt5那么火所以教程比较少，所以你的入门教程真的太有用了！！
虽然Lesson5 OpenCV那一课里新东西有点多把我搞懵逼了，但是继续往后看，边学边回头也基本懂了。
可以看得出来作者一路的学习成果，东西越做越成熟啦~

**Comment by se7enXF** [comment]
@dexter2406 上面我写了解决办法，以及暂时存在的问题。  
我在后续的代码中还是使用最开始的办法，虽然繁琐，但是逻辑清晰。各有所好吧。

**Comment by yewei9320** [comment]
'''@PySide2.QtCore.Slot(参数)
  def on_发送者对象名称_发射信号名称(self, 参数):
        pass'''
这里定义的名词不能是on_。。。，会与PySide2内部定义重名，改成其他名字就可以了，比如“oon_....”

**Comment by yewei9320** [comment]
on_sub2_signal_处定义的函数名不能为on_开头，与PySide2内部定义的缺省函数名重合，引起报错，改为以下例子即可
```    
    @QtCore.Slot()
    def sub2_signal(self):
        self.show_word.setText(random.choice(self.window().hello))
```
其他部分的槽函数定义名称不用改。这个也不知为什么没有影响。

**Comment by se7enXF** [comment]
> on_sub2_signal_处定义的函数名不能为on_开头，与PySide2内部定义的缺省函数名重合，引起报错，改为以下例子即可
> 
> ```
>     @QtCore.Slot()
>     def sub2_signal(self):
>         self.show_word.setText(random.choice(self.window().hello))
> ```
> 
> 其他部分的槽函数定义名称不用改。这个也不知为什么没有影响。

使用connectSlotsByName方式连接信号时，只需要指定控件的objectname，然后将on_objectname_signal()作为函数名，即可自动连接槽函数。在我的项目中，按钮，菜单等控件都可以正常传参，但是QTabWidget.currentChanged这个信号无作用。不知道我的描述你清楚了吗？我的QTabWidget已经自定义了objectname，不会冲突。

···python
# 传统方法
# 定义槽函数
def pushButton_slot_fun(self, x):
    print(x)
# 定义控件
push_word = QtWidgets.QPushButton('Random word')
# 槽连接
push_word.clicked.connect(lambda: pushButton_slot_fun('参数'))  


# connectSlotsByName方法
# 定义控件
push_word = QtWidgets.QPushButton('Random word')
# 必须设置控件的名称，即ObjectName
push_word.setObjectName('push_word')
# parent为发出槽信号的控件的parent，如是当前窗口的控件发出信号，这里填self
# 这句话必须在所有setObjectName之后才会生效
QtCore.QMetaObject.connectSlotsByName(parent)
# 用@QtCore.Slot()声明下面是槽函数
@QtCore.Slot()
# 槽函数名的格式为：on_[ObjectName]_[信号]
def on_push_word_clicked():
    pass
```
