### ISSUE TITLE
pyside2-uic生成py文件不是utf-8编码导致保存问题

### ISSUE THREAD

**Issue by MiSmiler** [se7enXF/pyside2#5]
发现了个bug，可能版本不同了吧。在[Lesson02](https://github.com/se7enXF/pyside2/tree/master/Lesson_02.%E4%BD%BF%E7%94%A8QtDesigner#2%E6%96%87%E4%BB%B6%E8%BD%AC%E6%8D%A2)中使用以下命令生成的`ui_mainwindow.py`文件是用utf-16编码，导致执行main.py的时候报错。
```bash
pyside2-uic [你保存的文件名].ui > ui_mainwindow.py
```
搜索后发现，将`>` 改成`-o`即可使用utf-8编码

**Comment by se7enXF** [comment]
@SpecialSmiler 非常感谢您提出的建议！但是经过我的调研，此问题不是`pyside2-uic(版本)`的问题，是你的操作系统（Shell）默认编码的问题。具体参考内容如下：
1. Qt官网提供的[使用样例](https://doc.qt.io/qtforpython-5/tutorials/basictutorial/uifiles.html)与我相同的脚本。
2. 在stackoverflow上有人提到了[类似的问题](https://stackoverflow.com/questions/53035340/pyside2-uic-null-bytes-in-output)，如果你使用的Windows操作系统，那么很大概率是相同的原因。
3. 这还有一个国外网友发表的建议[[Do not run PySide2-uic inside of PowerShell!](https://forum.freecadweb.org/viewtopic.php?f=22&t=46408&sid=239f2cba6835b6ba807352dd524f156b)]可以参考。
4. 如果你使用的IDE是近期版本的PyCharm，默认会将Terminal设置为`powershell.exe`，这很有可能造成此命令导出的文件编码不是我们所期望的，建议改回`cmd.exe`。

若有其他问题，欢迎提出！（当前问题若无疑问，请关闭此Issue，感谢支持！）

**Comment by MiSmiler** [comment]
太仔细啦！向你学习！
